Update odh-modelmesh-v2-13-push.yaml
Signed-off-by: Mohammadi Iram <89964724+MohammadiIram@users.noreply.github.com>

diff --git a/.tekton/odh-modelmesh-v2-13-push.yaml b/.tekton/odh-modelmesh-v2-13-push.yaml
--- a/.tekton/odh-modelmesh-v2-13-push.yaml
+++ b/.tekton/odh-modelmesh-v2-13-push.yaml
@@ -370,6 +370,17 @@ spec:
             script: |
               #!/bin/bash
               set -e
+              echo -e "\nGetting the list of built files (to be used later in the container build) ..."
+
+              # Verify the output file exists
+              if [[ ! -f "$PNC_CLI_OUTPUT_FILE" ]]; then
+                  echo "Error: $PNC_CLI_OUTPUT_FILE does not exist!"
+                  exit 1  # Exit if the file does not exist
+              fi
+              
+              # Check current directory and contents
+              echo "Current directory: $(pwd)"
+              ls -l "$(dirname "$PNC_CLI_OUTPUT_FILE")"
               jq '[.builds[].builtArtifacts[]?.downloadUrl]' "$PNC_CLI_OUTPUT_FILE" > "$(workspaces.source.path)/pnc-file-list.json"
               
               # Check if the pnc-file-list.json was created successfully
